name: Deploy Flutter Web to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Fix asset directory contents
        run: |
          mv build/web/assets/assets/* build/web/assets || true
          rmdir build/web/assets/assets || true
        
      - name: Build Flutter Web
        run: flutter build web --base-href="/planets-3a/"
        
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Add .nojekyll file
        run: touch ./build/web/.nojekyll
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
